# Generated by Django 6.0 on 2025-12-27 17:49

import django.db.models.deletion
import django.utils.timezone
import tutor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('WRITTEN', 'Schriftliche Prüfung'), ('ORAL', 'Mündliche Prüfung')], max_length=20)),
                ('max_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_mode', models.CharField(choices=[('FULL', 'Gesamtprüfung'), ('WRITTEN', 'Schriftliche Prüfung'), ('ORAL', 'Mündliche Prüfung')], max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(max_length=5)),
                ('total_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='Tutor', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('kakao', 'Kakao')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tutor.models.exam_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tutor.examrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='z.B. Leseverstehen, Hörverstehen', max_length=50)),
                ('name', models.CharField(help_text='z.B. Hören Teil1, Lesen Teil2', max_length=50)),
                ('is_question_based', models.BooleanField(default=True)),
                ('question_start_num', models.PositiveIntegerField(blank=True, null=True)),
                ('question_end_num', models.PositiveIntegerField(blank=True, null=True)),
                ('points_per_question', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('section_max_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tutor.exammodule')),
            ],
        ),
        migrations.AddField(
            model_name='examrecord',
            name='exam_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.examstandard'),
        ),
        migrations.AddField(
            model_name='exammodule',
            name='exam_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tutor.examstandard'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Männlich'), ('F', 'Weiblich')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField()),
                ('current_level', models.CharField(help_text='z.B. A2, B1', max_length=10)),
                ('target_level', models.CharField(help_text='z.B. B2, C1', max_length=10)),
                ('target_exam_mode', models.CharField(choices=[('FULL', 'Gesamtprüfung'), ('WRITTEN', 'Schriftliche Prüfung'), ('ORAL', 'Mündliche Prüfung')], default='FULL', max_length=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='examrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='tutor.student'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Fortschritt'), ('PAUSED', 'Pause'), ('FINISHED', 'Ende')], default='ACTIVE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='시간당 유로(€)', max_digits=6)),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tutor.student')),
            ],
            options={
                'verbose_name': 'Kursregistrierung',
                'verbose_name_plural': 'Kursregistrierungen',
            },
        ),
        migrations.CreateModel(
            name='ExamScoreInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_inputs', to='tutor.examrecord')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.examsection')),
            ],
            options={
                'unique_together': {('exam_record', 'exam_section')},
            },
        ),
        migrations.CreateModel(
            name='ExamDetailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_results', to='tutor.examrecord')),
                ('exam_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.examsection')),
            ],
            options={
                'unique_together': {('exam_record', 'exam_section', 'question_number')},
            },
        ),
    ]
