# Generated by Django 6.0 on 2026-01-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_exammodule_examrecord_examstandard_tutor_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name_manual', models.CharField(blank=True, help_text='선택지 없는 경우 직접 입력', max_length=100, null=True)),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('status', models.CharField(choices=[('PASSED', 'Bestanden'), ('FAILED', 'Nicht bestanden'), ('WAITING', 'Wartet auf Ergebnis')], default='WAITING', max_length=20)),
                ('total_score', models.CharField(blank=True, help_text='점수를 아는 경우 입력', max_length=50, null=True)),
                ('grade', models.CharField(blank=True, help_text='등급을 아는 경우 입력', max_length=20, null=True)),
                ('memo', models.TextField(blank=True, help_text='특이사항 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.examstandard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_results', to='tutor.student')),
            ],
            options={
                'verbose_name': 'Offizielles Prüfungsergebnis',
                'verbose_name_plural': 'Offizielle Prüfungsergebnisse',
                'ordering': ['-exam_date'],
            },
        ),
    ]
