# Generated by Django 6.0 on 2026-01-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_officialexamresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(blank=True, help_text='수업 주제 (예: Chapter 5)', max_length=200)),
                ('memo', models.TextField(blank=True, help_text='수업 피드백 또는 숙제')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Geplant'), ('COMPLETED', 'Abgeschlossen'), ('CANCELLED', 'Abgesagt'), ('NOSHOW', 'Unentschuldigt')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='tutor.courseregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutor.student')),
            ],
            options={
                'verbose_name': 'Unterrichtsstunde',
                'verbose_name_plural': 'Unterrichtsstunden',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
