# Generated by Django 6.0 on 2026-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Fortschritt'), ('PAUSED', 'Pause'), ('FINISHED', 'Ende')], default='ACTIVE', help_text='학생의 현재 수강 상태', max_length=10),
        ),
    ]
