# Generated by Django 6.0 on 2026-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_completed', 'priority', 'due_date', '-created_at'], 'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('PREP', 'Vorbereitung'), ('ADMIN', 'Verwaltung'), ('STUDENT', 'Betreuung'), ('PERSONAL', 'Privat')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Hoch'), (2, 'Mittel'), (3, 'Niedrig')], default=2),
        ),
    ]
