# Generated by Django 6.0 on 2026-01-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_todo_options_todo_category_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialexamresult',
            name='exam_mode',
            field=models.CharField(choices=[('FULL', 'Gesamtprüfung'), ('WRITTEN', 'Schriftliche Prüfung'), ('ORAL', 'Mündliche Prüfung')], default='FULL', help_text='응시 유형 (전체/필기/구술)', max_length=20),
        ),
    ]
