# Generated by Django 6.0 on 2026-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_officialexamresult_exam_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialexamresult',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='점수를 아는 경우 입력', max_digits=5, null=True),
        ),
    ]
