# Generated by Django 6.0 on 2026-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_alter_officialexamresult_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='memo',
            field=models.TextField(blank=True, help_text='계약 관련 특이사항', null=True),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
