# Generated by Django 6.0 on 2026-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_courseregistration_memo_examrecord_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='source',
            field=models.CharField(blank=True, help_text='모의고사 출처', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
