# Generated by Django 6.0 on 2026-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_examrecord_source_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetailresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='획득 점수 (부분 점수 포함)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='examsection',
            name='allow_partial_score',
            field=models.BooleanField(default=False, help_text='문항별 부분 점수 허용 여부 (True일 경우 O/X 대신 점수 입력)'),
        ),
    ]
