# Generated by Django 6.0 on 2026-02-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_examdetailresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, help_text='Straße, Nr, PLZ, Stadt', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='student',
            name='billing_name',
            field=models.CharField(blank=True, help_text='비워두면 학생 이름 사용 (학부모 이름 등)', max_length=100, verbose_name='Rechnungsempfänger'),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='업체명 (없으면 비워둠)', max_length=100, verbose_name='Firma')),
                ('manager_name', models.CharField(blank=True, help_text='대표자 이름', max_length=100, verbose_name='Geschäftsführer/-in')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Straße & Hausnummer')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Stadt')),
                ('country', models.CharField(default='Deutschland', max_length=50, verbose_name='Land')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail-Adresse')),
                ('website', models.URLField(blank=True, verbose_name='Webseite')),
                ('vat_id', models.CharField(blank=True, help_text='z.B. DE123456789', max_length=50, verbose_name='Umsatzsteuer-ID')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('is_small_business', models.BooleanField(default=False, help_text='체크 시 부가세(USt) 0% 적용 및 법적 면세 문구 자동 삽입', verbose_name='Kleinunternehmer')),
                ('price_input_type', models.CharField(choices=[('NETTO', 'Netto (zzgl. USt)'), ('BRUTTO', 'Brutto (inkl. USt)')], default='BRUTTO', help_text='상품 가격을 입력할 때 부가세를 포함한 가격인지 선택', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bankname')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='Kontoinhaber')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='Kontonummer')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='BLZ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('next_invoice_number', models.PositiveIntegerField(default=1000, help_text='다음 발행될 영수증 번호 (자동 증가)', verbose_name='Nächste Rechnungsnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(help_text='순차적 번호 (예: 1001)')),
                ('full_invoice_code', models.CharField(help_text='최종 송장 번호 (예: RE-10012601)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Rechnungsdatum (발행일)')),
                ('delivery_date_start', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum Start')),
                ('delivery_date_end', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum Ende')),
                ('due_date', models.DateField(help_text='납부 기한', verbose_name='Zahlungsziel')),
                ('sender_data', models.JSONField(default=dict, help_text='발행 시점의 BusinessProfile 데이터', verbose_name='Absenderdaten Snapshot')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Empfänger Name')),
                ('recipient_address', models.CharField(max_length=255, verbose_name='Empfänger Adresse')),
                ('subject', models.CharField(default='Rechnung', max_length=200, verbose_name='Betreff')),
                ('header_text', models.TextField(blank=True, help_text='인사말 및 서문 (HTML 허용)', verbose_name='Kopftext')),
                ('footer_text', models.TextField(blank=True, help_text='맺음말 및 안내 (HTML 허용)', verbose_name='Fußtext')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Netto Summe')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='USt Summe')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Brutto Summe')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_small_business', models.BooleanField(default=False, help_text='§19 UStG 적용 여부')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='tutor.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Menge')),
                ('unit', models.CharField(choices=[('pauschal', 'Pauschal'), ('Std', 'Stunden'), ('Tag(e)', 'Tage')], default='Std', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt %')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='USt %')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtpreis')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tutor.invoice')),
            ],
            options={
                'ordering': ['position_number'],
            },
        ),
    ]
