# Generated by Django 6.0 on 2026-02-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_student_address_student_billing_name_businessprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='Deutschland', max_length=50, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='student',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Straße & Hausnummer'),
        ),
    ]
