# Generated by Django 6.0 on 2026-02-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_remove_student_address_student_city_student_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='course_registration',
            field=models.OneToOneField(blank=True, help_text='이 영수증이 청구하는 대상 수강권', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='tutor.courseregistration'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='총 합계에서 차감할 할인 금액 (항상 양수로 저장, 계산 시 차감)', max_digits=10, verbose_name='Rabatt Betrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_label',
            field=models.CharField(blank=True, default='Gesamtrabatt', help_text='할인 항목 명칭 (예: 특별 할인)', max_length=100, verbose_name='Rabatt Bezeichnung'),
        ),
    ]
