# Generated by Django 6.0 on 2026-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_invoice_course_registration_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='default_intro_text',
            field=models.TextField(blank=True, default='<p>Sehr geehrte(r) Frau/Herr,</p>\n        <br>\n        <p>vielen Dank für Ihren Auftrag und das damit verbundene Vertrauen!</p>\n        <p>Hiermit stelle ich Ihnen die folgenden Leistungen in Rechnung:</p>\n        <br>\n        <p>Name: </p>\n        ', help_text='HTML 형식의 송장 기본 인사말 템플릿', verbose_name='Standard Kopftext'),
        ),
    ]
