# Generated by Django 6.0 on 2026-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_businessprofile_default_intro_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_label',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_label',
            field=models.CharField(blank=True, default='Gesamtrabatt', help_text='항목 명칭 (예: 특별 할인, 급행료)', max_length=100, verbose_name='Bezeichnung (Rabatt/Aufschlag)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_type',
            field=models.CharField(choices=[('DISCOUNT', 'Rabatt'), ('SURCHARGE', 'Aufschlag')], default='DISCOUNT', max_length=10, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_unit',
            field=models.CharField(choices=[('PERCENT', '%'), ('CURRENCY', 'EUR')], default='PERCENT', max_length=10, verbose_name='Einheit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='사용자가 입력한 숫자 (예: 10)', max_digits=10, verbose_name='Eingegebener Wert'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='계산된 조정 금액 (할인은 음수, 추가금은 양수로 저장될 수 있음)', max_digits=10, verbose_name='Berechneter Betrag'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_unit',
            field=models.CharField(choices=[('PERCENT', '%'), ('CURRENCY', 'EUR')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='입력된 할인 값', max_digits=10, verbose_name='Rabatt Wert'),
        ),
    ]
