# Generated by Django 6.0 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_remove_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='adjustment_label',
            field=models.CharField(blank=True, default='', help_text='항목 명칭 (예: 특별 할인, 급행료)', max_length=100, verbose_name='Bezeichnung (Rabatt/Aufschlag)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Stück'), ('HOUR', 'Stunde'), ('DAY', 'Tag'), ('FLAT_RATE', 'Pauschal')], default='PIECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (Netto)'),
        ),
    ]
