# Generated by Django 6.0 on 2026-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_alter_invoice_adjustment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='customer_number',
            field=models.CharField(blank=True, help_text='학생 고유 식별 번호 (예: KD-1001)', max_length=20, null=True, verbose_name='Kundennummer'),
        ),
    ]
