# Generated by Django 6.0 on 2026-02-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_student_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='customer_number',
            field=models.CharField(blank=True, help_text='학생 고유 식별 번호 (예: KD-1001)', max_length=20, unique=True, verbose_name='Kundennummer'),
        ),
    ]
