# Generated by Django 6.0 on 2026-02-08 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_student_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_label',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_unit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_value',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='발송 여부 (체크박스)', verbose_name='Versendet'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='default_intro_text',
            field=models.TextField(blank=True, default='\n        <p>Sehr geehrte(r) Frau/Herr,</p>\n        <p>vielen Dank für Ihren Auftrag und das damit verbundene Vertrauen!</p>\n        <p>Hiermit stelle ich Ihnen die folgenden Leistungen in Rechnung:</p>\n        <p>Name: </p>\n        ', help_text='HTML 형식의 송장 기본 인사말 템플릿', verbose_name='Standard Kopftext'),
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='Adjustment', max_length=100)),
                ('type', models.CharField(choices=[('DISCOUNT', 'Rabatt'), ('SURCHARGE', 'Aufschlag')], default='DISCOUNT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='입력값 (예: 10)', max_digits=10)),
                ('unit', models.CharField(choices=[('PERCENT', '%'), ('CURRENCY', 'EUR')], default='PERCENT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='계산된 유로 금액', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tutor.invoice')),
            ],
        ),
    ]
