# Generated by Django 6.0 on 2026-02-08 23:27

from django.db import migrations

def generate_customer_numbers(apps, schema_editor):
    Student = apps.get_model('tutor', 'Student')
    for student in Student.objects.all():
        if not student.customer_number:
            student.customer_number = f"KD-{student.id}"
            student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_remove_invoice_adjustment_label_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_customer_numbers),
    ]
