# Generated by Django 6.0 on 2026-02-08 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_alter_student_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_label',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_unit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='adjustment_value',
        ),
        migrations.AlterField(
            model_name='student',
            name='customer_number',
            field=models.CharField(blank=True, help_text='학생 고유 식별 번호 (예: KD-1001)', max_length=20, null=True, verbose_name='Kundennummer'),
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='Adjustment', max_length=100)),
                ('type', models.CharField(choices=[('DISCOUNT', 'Rabatt'), ('SURCHARGE', 'Aufschlag')], default='DISCOUNT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='입력값 (예: 10)', max_digits=10)),
                ('unit', models.CharField(choices=[('PERCENT', '%'), ('CURRENCY', 'EUR')], default='PERCENT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='계산된 유로 금액', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tutor.invoice')),
            ],
        ),
    ]
