# Generated by Django 6.0 on 2026-02-16 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_alter_student_customer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Schüler', 'verbose_name_plural': 'Schüler'},
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Firmenname (falls vorhanden)', max_length=100, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='is_small_business',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert: 0% USt und automatischer Hinweis auf §19 UStG', verbose_name='Kleinunternehmer'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='manager_name',
            field=models.CharField(blank=True, help_text='Name des Vertreters', max_length=100, verbose_name='Geschäftsführer/-in'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='next_invoice_number',
            field=models.PositiveIntegerField(default=1000, help_text='Nummer der nächsten Rechnung (wird automatisch erhöht)', verbose_name='Nächste Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='price_input_type',
            field=models.CharField(choices=[('NETTO', 'Netto (zzgl. USt)'), ('BRUTTO', 'Brutto (inkl. USt)')], default='BRUTTO', help_text='Wählen Sie, ob die eingegebenen Preise inklusive (Brutto) oder exklusive (Netto) USt sind.', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Stundensatz in Euro (€)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='memo',
            field=models.TextField(blank=True, help_text='Anmerkungen zum Vertrag', null=True),
        ),
        migrations.AlterField(
            model_name='examdetailresult',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Erreichte Punktzahl (inkl. Teilpunkte)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='source',
            field=models.CharField(blank=True, help_text='Quelle der Probeprüfung', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='allow_partial_score',
            field=models.BooleanField(default=False, help_text='Teilpunkte pro Frage erlauben (True: Punkteingabe, False: Richtig/Falsch)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course_registration',
            field=models.OneToOneField(blank=True, help_text='Zugehörige Kursregistrierung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='tutor.courseregistration'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Rechnungsdatum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(help_text='Fälligkeitsdatum', verbose_name='Zahlungsziel'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Schlusstext und Hinweise (HTML erlaubt)', verbose_name='Fußtext'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='full_invoice_code',
            field=models.CharField(help_text='Vollständige Rechnungsnummer (z.B. RE-10012601)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='header_text',
            field=models.TextField(blank=True, help_text='Einleitungstext (HTML erlaubt)', verbose_name='Kopftext'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(help_text='Fortlaufende Nummer (z.B. 1001)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Wurde die Rechnung bereits versendet?', verbose_name='Versendet'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_small_business',
            field=models.BooleanField(default=False, help_text='Anwendung der Kleinunternehmerregelung (§19 UStG)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sender_data',
            field=models.JSONField(default=dict, help_text='Snapshot der BusinessProfile-Daten zum Zeitpunkt der Erstellung', verbose_name='Absenderdaten Snapshot'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Summe der Anpassungen (Rabatte/Aufschläge)', max_digits=10, verbose_name='Berechneter Betrag'),
        ),
        migrations.AlterField(
            model_name='invoiceadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Berechneter Betrag in Euro', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceadjustment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wert (z.B. 10)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rabattwert', max_digits=10, verbose_name='Rabatt Wert'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='memo',
            field=models.TextField(blank=True, help_text='Feedback oder Hausaufgaben'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, help_text='Thema (z.B. Kapitel 5)', max_length=200),
        ),
        migrations.AlterField(
            model_name='officialexamresult',
            name='exam_mode',
            field=models.CharField(choices=[('FULL', 'Gesamtprüfung'), ('WRITTEN', 'Schriftliche Prüfung'), ('ORAL', 'Mündliche Prüfung')], default='FULL', help_text='Prüfungsart (Gesamt/Schriftlich/Mündlich)', max_length=20),
        ),
        migrations.AlterField(
            model_name='officialexamresult',
            name='exam_name_manual',
            field=models.CharField(blank=True, help_text='Eigene Eingabe (falls nicht in der Liste)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='officialexamresult',
            name='grade',
            field=models.CharField(blank=True, help_text='Note (falls bekannt)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='officialexamresult',
            name='memo',
            field=models.TextField(blank=True, help_text='Anmerkungen', null=True),
        ),
        migrations.AlterField(
            model_name='officialexamresult',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punktzahl (falls bekannt)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='billing_name',
            field=models.CharField(blank=True, help_text='Falls abweichend vom Schülernamen (z.B. Elternteil)', max_length=100, verbose_name='Rechnungsempfänger'),
        ),
        migrations.AlterField(
            model_name='student',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Eindeutige Kundennummer (z.B. KD-1001)', max_length=20, unique=True, verbose_name='Kundennummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Fortschritt'), ('PAUSED', 'Pause'), ('FINISHED', 'Ende')], default='ACTIVE', help_text='Aktueller Status des Schülers', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='provider',
            field=models.CharField(choices=[('email', 'E-mail'), ('google', 'Google'), ('kakao', 'Kakao')], default='email', max_length=20),
        ),
    ]
