# Generated by Django 6.0 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_alter_businessprofile_default_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='발송 여부 (체크박스)', verbose_name='Versendet'),
        ),
    ]
