# Generated by Django 6.0 on 2026-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum Eingabe'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Entwurf gespeichert oder final bestätigt', verbose_name='Finalisiert'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_mode',
            field=models.CharField(choices=[('BRUTTO', 'Brutto'), ('NETTO', 'Netto')], default='BRUTTO', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Referenznummer'),
        ),
    ]
