# Generated by Django 6.0 on 2026-03-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0025_fix_legacy_student_customer_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='recipient_address',
            field=models.JSONField(default=dict, help_text='Strukturierte Empfängeradresse mit Straße, PLZ, Ort und Land', verbose_name='Empfänger Adresse'),
        ),
    ]
