"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is not set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

hosts = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = hosts.split(",") if hosts else []


# Application definition

INSTALLED_APPS = [
    # 1. Django Basic
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Required by allauth to manage site-specific data
    # allauth가 사이트별 데이터를 관리하기 위해 필수
    "django.contrib.sites",
    
    # 2. Third-party Apps (Core)
    # The core library for building Web APIs
    # 웹 API 구축을 위한 핵심 라이브러리
    "rest_framework",
    
    # Provides token-based authentication (Required by dj-rest-auth)
    # 토큰 기반 인증 제공 (dj-rest-auth 사용 시 필수)
    "rest_framework.authtoken",

    # Handles Cross-Origin Resource Sharing (CORS) for React communication
    # 리액트와의 통신을 위한 교차 출처 리소스 공유(CORS) 처리
    "corsheaders",

    # Exposes authentication logic (login/logout) as REST APIs
    # 인증 로직(로그인/로그아웃)을 REST API로 노출
    "dj_rest_auth",

    # Enables registration endpoints for social login support
    # 소셜 로그인 지원을 위한 회원가입 엔드포인트 활성화
    "dj_rest_auth.registration",

    # 3. Allauth (Auth Logic)
    # Core application for comprehensive authentication management
    # 포괄적인 인증 관리를 위한 핵심 애플리케이션
    "allauth",

    # Manages local email/password based accounts
    # 이메일/비밀번호 기반의 로컬 계정 관리
    "allauth.account",

    # Manages social account authentication flows
    # 소셜 계정 인증 흐름 관리
    "allauth.socialaccount",

    # 4. Social Providers
    # Google OAuth provider
    # 구글 로그인 제공자
    "allauth.socialaccount.providers.google",

    # Kakao OAuth provider
    # 카카오 로그인 제공자
    "allauth.socialaccount.providers.kakao",

    # 5. Dev Tools
    # Generates fake data for testing purposes
    # 테스트 목적으로 가짜 데이터 생성
    "django_seed",

    # Adds extra features to the Django CLI
    # Django CLI에 추가 기능 제공
    "django_extensions",

    # 6. Local Apps
    # Add project apps 
    # 프로젝트 앱
]

# Unique ID for the current site (Required by sites framework)
# 현재 사이트의 고유 ID (sites 프레임워크 필수 설정)
SITE_ID = 1

MIDDLEWARE = [
    # Should be at the top to handle headers before other requests
    # 다른 요청보다 먼저 헤더를 처리하기 위해 최상단에 위치해야 함
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    # Serves static files efficiently in production
    # 배포 환경에서 정적 파일을 효율적으로 제공
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Middleware required for allauth functionality
    # allauth 기능 작동에 필요한 미들웨어
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def get_env_variable(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = f"Set the {var_name} environment variable in your .env file."
        raise ImproperlyConfigured(error_msg)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME'),       
        'USER': get_env_variable('DB_USER'),         
        'PASSWORD': get_env_variable('DB_PASSWORD'), 
        'HOST': os.getenv('DB_HOST', 'localhost'),      
        'PORT': os.getenv('DB_PORT', '5432'),           
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
