"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 프로젝트 내부 경로 생성 예시: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# .env 파일에서 환경변수 로드
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is not set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Define allowed hosts (domain names/IPs) that can serve this site
# 이 사이트를 서비스할 수 있는 허용된 호스트(도메인/IP) 정의
hosts = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = hosts.split(",") 

# Base URLs for Frontend and Backend separation
# 프론트엔드와 백엔드 분리 구조를 위한 기본 URL 설정
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://127.0.0.1:5173")
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL", "http://127.0.0.1:8000")

# OAuth callback URLs constructed dynamically
# 동적으로 생성되는 OAuth 콜백 URL
GOOGLE_CALLBACK_URL = f"{BACKEND_BASE_URL}/api/social/login/google/callback/"
KAKAO_CALLBACK_URL = f"{BACKEND_BASE_URL}/api/social/login/kakao/callback/"

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Required for 'allauth' specific site handling
    # 'allauth'의 사이트별 처리 기능을 위해 필수
    "django.contrib.sites",
]

THIRD_PARTY_APPS = [
    # REST Framework & Authentication
    # REST 프레임워크 및 인증 관련
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    
    # CORS Headers for frontend communication
    # 프론트엔드 통신을 위한 CORS 헤더
    "corsheaders",
    
    # Allauth for Social Login
    # 소셜 로그인을 위한 Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.kakao",
    
    # Development Utilities
    # 개발 편의 도구
    "django_seed",
    "django_extensions",
    
    # Advanced filtering support
    # 고급 필터링 기능 지원
    "django_filters",
    
    # Email handling
    # 이메일 처리
    "anymail",
]

LOCAL_APPS = [
    "tutor.apps.TutorConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Site ID required by django.contrib.sites
# django.contrib.sites 사용을 위한 사이트 ID 식별자
SITE_ID = 1

MIDDLEWARE = [
    # CORS middleware must be placed as high as possible to handle preflight requests
    # 프리플라이트 요청 처리를 위해 CORS 미들웨어는 가능한 최상단에 위치해야 함
    "corsheaders.middleware.CorsMiddleware",
    
    # Enforces security enhancements (e.g., SSL redirect, XSS protection)
    # 보안 강화 (SSL 리다이렉트, XSS 보호 등) 적용
    "django.middleware.security.SecurityMiddleware",
    
    # Optimized static file serving for production
    # 배포 환경을 위한 최적화된 정적 파일 서빙
    "whitenoise.middleware.WhiteNoiseMiddleware",
    
    # Manages user sessions across requests
    # 요청 간 사용자 세션 관리
    "django.contrib.sessions.middleware.SessionMiddleware",
    
    # Adds common functionality (e.g., forbidding access to user agents)
    # 일반적인 기능 추가 (예: 특정 사용자 에이전트 접근 금지 등)
    "django.middleware.common.CommonMiddleware",
    
    # Protects against Cross-Site Request Forgery (CSRF)
    # 사이트 간 요청 위조(CSRF) 공격 방지
    "django.middleware.csrf.CsrfViewMiddleware",
    
    # Associates users with requests using sessions
    # 세션을 사용하여 사용자와 요청을 연결 (인증 처리)
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    
    # Enables cookie- and session-based message storage
    # 쿠키 및 세션 기반 메시지 저장 기능 활성화
    "django.contrib.messages.middleware.MessageMiddleware",
    
    # Protects against clickjacking
    # 클릭재킹 공격 방지
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # Middleware for allauth account management
    # allauth 계정 관리를 위한 미들웨어
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration using dj-database-url for flexibility
# 유연성을 위한 dj-database-url을 이용한 데이터베이스 설정
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
    
    # Custom password validator to enforce specific complexity requirements
    # 특정 복잡성 요구 사항을 적용하기 위한 커스텀 비밀번호 검증기
    {
        "NAME": "tutor.validators.CustomPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise static files storage for efficient serving in production
# 배포 환경에서 효율적인 서빙을 위한 WhiteNoise 정적 파일 스토리지
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media configuration for user-uploaded files
# 사용자 업로드 파일을 위한 미디어 설정
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Custom user model definition
# 커스텀 유저 모델 지정
AUTH_USER_MODEL = "tutor.Tutor"

# ==========================================
# Authentication & REST Configuration
# ==========================================

# Configure authentication backends for Admin and Allauth
# 관리자 및 Allauth 인증을 위한 백엔드 구성
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth & dj-rest-auth compatibility settings
# Allauth와 dj-rest-auth 간의 호환성 설정
ACCOUNT_LOGIN_METHODS = {"email"}

# Fields required during signup
# 가입 시 필수 입력 필드
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
]

ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

# Email verification settings
# 이메일 인증 필수
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True

# Account registration settings
# 계정 등록 설정
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_ADAPTER = "tutor.adapters.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "tutor.adapters.CustomSocialAccountAdapter"


# Email Configuration (Brevo API / Anymail)
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
ANYMAIL = {
    "BREVO_API_KEY": os.environ.get("BREVO_API_KEY"),
}
DEFAULT_FROM_EMAIL = "audrbs92@gmail.com"

# Login/Logout redirects
# 로그인/로그아웃 리다이렉트
LOGIN_REDIRECT_URL = "/api/social/callback/"
ACCOUNT_LOGOUT_REDIRECT_URL = f"{FRONTEND_BASE_URL}/login"

# JWT configuration (dj-rest-auth)
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "my-app-auth",
    "JWT_AUTH_REFRESH_COOKIE": "my-app-refresh-token",
    
    # Secure adjustments for development
    # 개발 환경 보안 조정
    # Changed: Set HTTPONLY to True to prevent XSS attacks
    # 변경사항: XSS 공격 방지를 위해 HTTPONLY를 True로 설정
    "JWT_AUTH_SECURE": True,
    "JWT_AUTH_HTTPONLY": True,
    "JWT_AUTH_SAMESITE": "None",
    "JWT_AUTH_COOKIE_DOMAIN": None,
    
    # Disable CSRF check for cookie-based auth in this setup
    # 현재 설정에서 쿠키 기반 인증을 위한 CSRF 체크 비활성화
    "JWT_AUTH_COOKIE_USE_CSRF": False,
    "SESSION_LOGIN": False,
    
    # Password change settings
    # 비밀번호 변경 설정
    "OLD_PASSWORD_FIELD_ENABLED": True,
    "LOGOUT_ON_PASSWORD_CHANGE": False,
    "PASSWORD_RESET_CONFIRM_URL": "password-reset/confirm",
    
    # Serializers
    # 시리얼라이저 설정
    "USER_DETAILS_SERIALIZER": "tutor.serializers.TutorSerializer",
    "REGISTER_SERIALIZER": "tutor.serializers.CustomRegisterSerializer",
    "PASSWORD_CHANGE_SERIALIZER": "tutor.serializers.CustomPasswordChangeSerializer",
    "PASSWORD_RESET_SERIALIZER": "tutor.serializers.CustomPasswordResetSerializer",
    "PASSWORD_RESET_CONFIRM_SERIALIZER": "tutor.serializers.CustomPasswordResetConfirmSerializer",
}

# Security settings for Production
# 배포 환경을 위한 보안 설정
if not DEBUG:

    # Enforce HTTPS and browser security headers
    # HTTPS 강제 적용 및 브라우저 보안 헤더 설정
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SIMPLE_JWT = {
    # Token validity periods
    # 토큰 유효 기간 설정
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    
    # Enable refresh token rotation (new refresh token on use)
    # 리프레시 토큰 로테이션 활성화 (사용 시 새로운 리프레시 토큰 발급)
    "ROTATE_REFRESH_TOKENS": True,
    
    # Blacklist old refresh tokens after rotation
    # 로테이션 후 이전 리프레시 토큰을 블랙리스트 처리 (재사용 방지)
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": SECRET_KEY,
}

# Social login configuration using django-allauth
# django-allauth를 이용한 소셜 로그인 설정
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "kakao": {
        "APP": {
            "client_id": os.environ.get("KAKAO_CLIENT_ID"),
            "secret": os.environ.get("KAKAO_CLIENT_SECRET"),
            "key": "",
        },
    },
}

# CORS Configuration
# CORS 설정
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# Define base allowed origins for development and production
# 개발 및 배포를 위한 기본 허용 출처 정의
base_origins = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://ms-planer.up.railway.app",  
    "https://ms-planer-backend.up.railway.app",
]

# Load allowed origins from environment variable or use defaults
# 환경변수에서 허용 출처 로드 또는 기본값 사용
cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if cors_origins_env:

    extra_origins = [origin.strip() for origin in cors_origins_env.split(",")]
    CORS_ALLOWED_ORIGINS = base_origins + extra_origins
    CSRF_TRUSTED_ORIGINS = base_origins + extra_origins
else:

    # Default local development origins
    # 기본 로컬 개발 출처
    CORS_ALLOWED_ORIGINS = base_origins
    CSRF_TRUSTED_ORIGINS = base_origins

# Social Login HTTPS Setting (Crucial for Production!)
# 소셜 로그인 시 HTTPS 프로토콜 강제 (이게 없으면 소셜 로그인 에러 남)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # Prioritize JWT Cookie Authentication for stateless API requests
        # 상태가 없는 API 요청을 위해 JWT 쿠키 인증을 최우선으로 설정합니다
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
        
        # Add SessionAuthentication to support initial social login sync
        # 초기 소셜 로그인 동기화를 지원하기 위해 세션 인증을 추가합니다
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    
    # Global default filter backend setup
    # 전역 기본 필터 백엔드 설정
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_HTTPONLY = False
    CSRF_COOKIE_HTTPONLY = False
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None
